export const translations = {
    English: {
        welcome: "Welcome",
        facultyDashboard: "Faculty Dashboard",
        dashboard: "Dashboard",
        overview: "Overview",
        attendanceHub: "Attendance Hub",
        leaveGateway: "Leave Gateway",
        curriculum: "Curriculum",
        curriculumHub: "Curriculum Hub",
        settings: "Settings",
        myIdentity: "My Identity",
        totalStudents: "Total Students",
        avgAttendance: "Avg Attendance",
        pendingRecords: "Pending Records",
        liveClasses: "Live Classes",
        registryFinalized: "Registry Finalized",
        studentRegistry: "Student Registry",
        exportMaster: "Export Master",
        viewReports: "View Reports",
        finalizeRegistry: "Finalize Registry",
        recentClassActivity: "Recent Class Activity",
        sessionProtocols: "Session Protocols",
        teamMembers: "The Team Members",
        studentRegistryOffline: "Student Registry Offline",
        dbSyncMsg: "Connect to the central database to synchronize and view student records.",
        viewDirectory: "View Student Directory",
        dbRequired: "Database Connection Required",
        facultyAttendanceEntry: "Faculty Attendance Entry",
        memberDirectory: "Member Directory",
        downloadRegistry: "Download Registry",
        generateReport: "Generate Report",
        darkInterface: "Dark Interface",
        updateAccessKey: "Update Access Key",
        deleteAccount: "Delete Account",
        terminateNode: "Terminate Node",
        logoutSession: "Logout Session",
        parentSmsLogging: "Parent SMS Telemetry Logging",
        outboundLogs: "Outbound Alert Logs",
        sandboxGateway: "Interactive Sandbox Gateway",
        transmitSandboxAlert: "Transmit Sandbox Alert",
        parentMobileNo: "Parent Mobile Number",
        studentNameOptional: "Student Name (Optional)",
        msgPayloadOptional: "Message Payload (Optional)",
        smsConsoleSubtitle: "Outbound SMS transmissions, delivery status auditing, and sandboxed manual triggers",
        smsSandboxDesc: "Verify gateway cellular transmission. Valid international numbers are required for Textbelt dispatches.",
        reloadConsole: "Reload Console",
        globalLanguage: "Global Language",
        portalConfig: "Portal Configuration",
        sysPreferences: "System preferences and operational parameters",
        interfaceProtocols: "Interface Protocols",
        telemetryAlerts: "Telemetry Alerts",
        telemetryDesc: "Receive real-time notifications about node status",
        darkDesc: "Optimize visual output for low-light environments",
        portalConfigTitle: "Portal Configuration",
        securityMatrix: "Security Matrix",
        pinRequired: "PIN REQUIRED",
        criticalZone: "Critical Zone",
        accountTerminationDesc: "Account termination is an irreversible operational command.",
        automationProtocols: "Attendance Automation Protocols",
        automationSubtitle: "Configure background engines and simulation telemetry overrides",
        automationParameters: "Automation Parameters",
        autoAbsentSweep: "Automated Absent Sweep",
        autoAbsentSweepDesc: "Sweeps and marks inactive/pending students absent daily at cutoff time",
        sweepCutoffTime: "Sweep Cutoff Time",
        parentEmailNotify: "Parent Email Notifications",
        parentEmailNotifyDesc: "Dispatches email telemetry alerts directly to parents when marked absent",
        parentSmsNotify: "Parent SMS Notifications",
        parentSmsNotifyDesc: "Dispatches real-time SMS alerts directly to parent mobile numbers on absence",
        midnightSessionReset: "Midnight Session Reset",
        midnightSessionDesc: "Automatic cycle daily restoration",
        telemetryOverrides: "Telemetry Overrides",
        simulationDesc: "Forces instant manual simulation of background services for live demonstration or instant verification cycles.",
        simulateSweep: "Simulate End-of-Day Sweep",
        simulateReset: "Simulate Midnight Cycle Reset",
        forceSweep: "FORCE SWEEP",
        forceReset: "FORCE RESET"
    },
    Spanish: {
        welcome: "Bienvenido",
        facultyDashboard: "Panel de la Facultad",
        dashboard: "Tablero",
        overview: "Resumen",
        attendanceHub: "Centro de Asistencia",
        leaveGateway: "Pasarela de Permisos",
        curriculum: "Currículo",
        curriculumHub: "Centro de Currículo",
        settings: "Configuración",
        myIdentity: "Mi Identidad",
        totalStudents: "Estudiantes Totales",
        avgAttendance: "Asistencia Promed",
        pendingRecords: "Registros Pendientes",
        liveClasses: "Clases en Vivo",
        registryFinalized: "Registro Finalizado",
        studentRegistry: "Registro de Estudiantes",
        exportMaster: "Exportar Maestro",
        viewReports: "Ver Informes",
        finalizeRegistry: "Finalizar Registro",
        recentClassActivity: "Actividad Reciente",
        sessionProtocols: "Protocolos de Sesión",
        teamMembers: "Miembros del Equipo",
        studentRegistryOffline: "Registro de Estudiantes Desconectado",
        dbSyncMsg: "Conéctese a la base de datos central para sincronizar y ver registros.",
        viewDirectory: "Ver Directorio de Alumnos",
        dbRequired: "Conexión a Base de Datos Requerida",
        facultyAttendanceEntry: "Registro Asistencia Facultad",
        memberDirectory: "Directorio de Miembros",
        downloadRegistry: "Descargar Registro",
        generateReport: "Generar Informe",
        darkInterface: "Interfaz Oscura",
        updateAccessKey: "Actualizar Llave",
        deleteAccount: "Eliminar Cuenta",
        terminateNode: "Terminar Nodo",
        logoutSession: "Cerrar Sesión",
        parentSmsLogging: "Registro de Telemetría SMS",
        outboundLogs: "Alertas de Salida",
        sandboxGateway: "Pasarela de Pruebas",
        transmitSandboxAlert: "Transmitir Alerta de Prueba",
        parentMobileNo: "Número Móvil del Padre",
        studentNameOptional: "Nombre del Alumno (Opcional)",
        msgPayloadOptional: "Mensaje (Opcional)",
        smsConsoleSubtitle: "Transmisiones SMS salientes, auditoría de entrega y pruebas manuales",
        smsSandboxDesc: "Verificar transmisión celular. Se requieren números internacionales válidos para Textbelt.",
        reloadConsole: "Recargar Consola",
        globalLanguage: "Idioma Global",
        portalConfig: "Configuración del Portal",
        sysPreferences: "Preferencias del sistema y parámetros operativos",
        interfaceProtocols: "Protocolos de Interfaz",
        telemetryAlerts: "Alertas de Telemetría",
        telemetryDesc: "Reciba notificaciones en tiempo real sobre el estado del nodo",
        darkDesc: "Optimizar la visualización para entornos de poca luz",
        portalConfigTitle: "Configuración del Portal",
        securityMatrix: "Matriz de Seguridad",
        pinRequired: "PIN REQUERIDO",
        criticalZone: "Zona Crítica",
        accountTerminationDesc: "La terminación de la cuenta es un comando operativo irreversible.",
        automationProtocols: "Protocolos de Automatización",
        automationSubtitle: "Configurar motores en segundo plano y simulaciones",
        automationParameters: "Parámetros de Automatización",
        autoAbsentSweep: "Barrido Automático de Ausencias",
        autoAbsentSweepDesc: "Barre y marca como ausentes a los alumnos pendientes diariamente",
        sweepCutoffTime: "Hora de Corte",
        parentEmailNotify: "Notificaciones por Email",
        parentEmailNotifyDesc: "Envía correos electrónicos directamente a los padres en caso de ausencia",
        parentSmsNotify: "Notificaciones por SMS",
        parentSmsNotifyDesc: "Envía alertas SMS en tiempo real directamente al móvil de los padres en caso de ausencia",
        midnightSessionReset: "Restablecimiento de Medianoche",
        midnightSessionDesc: "Restauración diaria automática del ciclo",
        telemetryOverrides: "Simuladores de Telemetría",
        simulationDesc: "Fuerza la simulación instantánea de servicios para demostraciones o pruebas rápidas.",
        simulateSweep: "Simular Fin del Día",
        simulateReset: "Simular Reinicio Diario",
        forceSweep: "FORZAR BARRIDO",
        forceReset: "FORZAR REINICIO"
    },
    Hindi: {
        welcome: "स्वागत है",
        facultyDashboard: "संकाय डैशबोर्ड",
        dashboard: "डैशबोर्ड",
        overview: "अवलोकन",
        attendanceHub: "उपस्थिति हब",
        leaveGateway: "छुट्टी गेटवे",
        curriculum: "पाठ्यक्रम",
        curriculumHub: "पाठ्यक्रम हब",
        settings: "सेटिंग्स",
        myIdentity: "मेरी पहचान",
        totalStudents: "कुल छात्र",
        avgAttendance: "औसत उपस्थिति",
        pendingRecords: "लंबित रिकॉर्ड",
        liveClasses: "लाइव कक्षाएं",
        registryFinalized: "रजिस्ट्री पूरी हुई",
        studentRegistry: "छात्र रजिस्ट्री",
        exportMaster: "मास्टर निर्यात",
        viewReports: "रिपोर्ट देखें",
        finalizeRegistry: "रजिस्ट्री पूर्ण करें",
        recentClassActivity: "हाल की कक्षा गतिविधि",
        sessionProtocols: "सत्र प्रोटोकॉल",
        teamMembers: "टीम के सदस्य",
        studentRegistryOffline: "छात्र रजिस्ट्री ऑफ़लाइन",
        dbSyncMsg: "छात्र रिकॉर्ड को सिंक्रनाइज़ और देखने के लिए केंद्रीय डेटाबेस से कनेक्ट करें।",
        viewDirectory: "छात्र निर्देशिका देखें",
        dbRequired: "डेटाबेस कनेक्शन आवश्यक",
        facultyAttendanceEntry: "संकाय उपस्थिति प्रविष्टि",
        memberDirectory: "सदस्य निर्देशिका",
        downloadRegistry: "रजिस्ट्री डाउनलोड करें",
        generateReport: "रिपोर्ट तैयार करें",
        darkInterface: "डार्क इंटरफ़ेस",
        updateAccessKey: "एक्सेस कुंजी बदलें",
        deleteAccount: "खाता हटाएं",
        terminateNode: "नोड समाप्त करें",
        logoutSession: "लॉगआउट करें",
        parentSmsLogging: "अभिभावक एसएमएस टेलीमेट्री",
        outboundLogs: "आउटबाउंड अलर्ट लॉग",
        sandboxGateway: "इंटरएक्टिव सैंडबॉक्स गेटवे",
        transmitSandboxAlert: "सैंडबॉक्स अलर्ट भेजें",
        parentMobileNo: "अभिभावक मोबाइल नंबर",
        studentNameOptional: "छात्र का नाम (वैकल्पिक)",
        msgPayloadOptional: "संदेश सामग्री (वैकल्पिक)",
        smsConsoleSubtitle: "एसएमएस प्रसारण, वितरण स्थिति ऑडिटिंग, और परीक्षण विकल्प",
        smsSandboxDesc: "गेटवे मोबाइल नेटवर्क का परीक्षण करें। टेक्स्टबेल्ट के लिए वैध नंबर आवश्यक हैं।",
        reloadConsole: "कंसोल रीलोड करें",
        globalLanguage: "वैश्विक भाषा",
        portalConfig: "पोर्टल कॉन्फ़िगरेशन",
        sysPreferences: "सिस्टम प्राथमिकताएं और परिचालन पैरामीटर",
        interfaceProtocols: "इंटरफ़ेस प्रोटोकॉल",
        telemetryAlerts: "टेलीमेट्री अलर्ट",
        telemetryDesc: "नोड स्थिति के बारे में वास्तविक समय सूचनाएं प्राप्त करें",
        darkDesc: "कम रोशनी वाले वातावरण के लिए विज़ुअल अनुकूलित करें",
        portalConfigTitle: "पोर्टल कॉन्फ़िगरेशन",
        securityMatrix: "सुरक्षा मैट्रिक्स",
        pinRequired: "पिन आवश्यक है",
        criticalZone: "महत्वपूर्ण क्षेत्र",
        accountTerminationDesc: "खाता हटाना एक अपरिवर्तनीय परिचालन आदेश है।",
        automationProtocols: "उपस्थिति स्वचालन प्रोटोकॉल",
        automationSubtitle: "बैकग्राउंड इंजन और सिमुलेशन पैरामीटर कॉन्फ़िगर करें",
        automationParameters: "स्वचालन पैरामीटर",
        autoAbsentSweep: "स्वचालित अनुपस्थित स्वीप",
        autoAbsentSweepDesc: "कटऑफ समय पर प्रतिदिन लंबित छात्रों को अनुपस्थित चिह्नित करता है",
        sweepCutoffTime: "स्वीप कटऑफ समय",
        parentEmailNotify: "अभिभावक ईमेल सूचनाएं",
        parentEmailNotifyDesc: "अनुपस्थित होने पर सीधे अभिभावकों को ईमेल अलर्ट भेजता है",
        parentSmsNotify: "अभिभावक एसएमएस सूचनाएं",
        parentSmsNotifyDesc: "अनुपस्थित होने पर सीधे अभिभावक के मोबाइल पर वास्तविक समय एसएमएस अलर्ट भेजता है",
        midnightSessionReset: "मध्यरात्रि सत्र रीसेट",
        midnightSessionDesc: "स्वचालित दैनिक रीसेट चक्र",
        telemetryOverrides: "टेलीमेट्री सिमुलेटर",
        simulationDesc: "त्वरित लाइव प्रदर्शन या सत्यापन के लिए बैकग्राउंड सेवाओं का तुरंत सिमुलेशन करता है।",
        simulateSweep: "दैनिक स्वीप सिमुलेशन",
        simulateReset: "दैनिक रीसेट सिमुलेशन",
        forceSweep: "स्वीप लागू करें",
        forceReset: "रीसेट लागू करें"
    },
    Kannada: {
        welcome: "ಸ್ವಾಗತ",
        facultyDashboard: "ಬೋಧಕ ಸಿಬ್ಬಂದಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        overview: "ಅವಲೋಕನ",
        attendanceHub: "ಹಾಜರಾತಿ ಕೇಂದ್ರ",
        leaveGateway: "ರಜೆ ಗೇಟ್‌ವೇ",
        curriculum: "ಪಠ್ಯಕ್ರಮ",
        curriculumHub: "ಪಠ್ಯಕ್ರಮ ಕೇಂದ್ರ",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        myIdentity: "ನನ್ನ ಗುರುತು",
        totalStudents: "ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು",
        avgAttendance: "ಸರಾಸರಿ ಹಾಜರಾತಿ",
        pendingRecords: "ಬಾಕಿ ದಾಖಲೆಗಳು",
        liveClasses: "ಲೈವ್ ತರಗತಿಗಳು",
        registryFinalized: "ದಾಖಲಾತಿ ಪೂರ್ಣಗೊಂಡಿದೆ",
        studentRegistry: "ವಿದ್ಯಾರ್ಥಿ ದಾಖಲಾತಿ",
        exportMaster: "ಮಾಸ್ಟರ್ ರಫ್ತು",
        viewReports: "ವರದಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        finalizeRegistry: "ದಾಖಲಾತಿ ಅಂತಿಮಗೊಳಿಸಿ",
        recentClassActivity: "ತರಗತಿಯ ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
        sessionProtocols: "ಸಭೆಯ ಪ್ರೋಟೋಕಾಲ್ಗಳು",
        teamMembers: "ತಂಡದ ಸದಸ್ಯರು",
        studentRegistryOffline: "ವಿದ್ಯಾರ್ಥಿ ದಾಖಲಾತಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದೆ",
        dbSyncMsg: "ವಿದ್ಯಾರ್ಥಿ ದಾಖಲೆಗಳನ್ನು ಸಿಂಕ್ ಮಾಡಲು ಮತ್ತು ವೀಕ್ಷಿಸಲು ಕೇಂದ್ರೀಯ ಡೇಟಾಬೇಸ್‌ಗೆ ಸಂಪರ್ಕಪಡಿಸಿ.",
        viewDirectory: "ವಿದ್ಯಾರ್ಥಿ ಡೈರೆಕ್ಟರಿ ವೀಕ್ಷಿಸಿ",
        dbRequired: "ಡೇಟಾಬೇಸ್ ಸಂಪರ್ಕದ ಅವಶ್ಯಕತೆಯಿದೆ",
        facultyAttendanceEntry: "ಸಿಬ್ಬಂದಿ ಹಾಜರಾತಿ ನಮೂದು",
        memberDirectory: "ಸದಸ್ಯರ ಡೈರೆಕ್ಟರಿ",
        downloadRegistry: "ದಾಖಲಾತಿ ಡೌನ್‌ಲೋಡ್",
        generateReport: "ವರದಿ ಸಿದ್ಧಪಡಿಸಿ",
        darkInterface: "ಡಾರ್ಕ್ ಮೋಡ್",
        updateAccessKey: "ಪ್ರವೇಶ ಕೀ ಬದಲಾಯಿಸಿ",
        deleteAccount: "ಖಾತೆ ಅಳಿಸಿ",
        terminateNode: "ಖಾತೆ ಮುಚ್ಚಿ",
        logoutSession: "ಲಾಗ್ ಔಟ್",
        parentSmsLogging: "ಪೋಷಕರ ಎಸ್ಎಂಎಸ್ ಟೆಲಿಮೆಟ್ರಿ",
        outboundLogs: "ಹೊರಹೋಗುವ ಎಸ್ಎಂಎಸ್ ಇತಿಹಾಸ",
        sandboxGateway: "ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಟೆಸ್ಟಿಂಗ್",
        transmitSandboxAlert: "ಟೆಸ್ಟ್ ಎಸ್ಎಂಎಸ್ ಕಳುಹಿಸಿ",
        parentMobileNo: "ಪೋಷಕರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        studentNameOptional: "ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು (ಐಚ್ಛಿಕ)",
        msgPayloadOptional: "ಸಂದೇಶದ ಮಾಹಿತಿ (ಐಚ್ಛಿಕ)",
        smsConsoleSubtitle: "ಹೊರಹೋಗುವ ಎಸ್ಎಂಎಸ್ ಪ್ರಸಾರಗಳು, ವಿತರಣಾ ಸ್ಥಿತಿ ಆಡಿಟಿಂಗ್ ಮತ್ತು ಟೆಸ್ಟಿಂಗ್ ಪ್ರಚೋದಕಗಳು",
        smsSandboxDesc: "ಮೊಬೈಲ್ ಪ್ರಸಾರವನ್ನು ಪರಿಶೀಲಿಸಿ. ಟೆಕ್ಸ್ಟ್‌ಬೆಲ್ ರಫ್ತು ಮಾಡಲು ಮಾನ್ಯ ಅಂತರರಾಷ್ಟ್ರೀಯ ಸಂಖ್ಯೆಗಳು ಅಗತ್ಯವಿದೆ.",
        reloadConsole: "ರೀಲೋಡ್ ಮಾಡಿ",
        globalLanguage: "ಜಾಗತಿಕ ಭಾಷೆ",
        portalConfig: "ಪೋರ್ಟಲ್ ಕಾನ್ಫಿಗರೇಶನ್",
        sysPreferences: "ಸಿಸ್ಟಮ್ ಆದ್ಯತೆಗಳು ಮತ್ತು ಕಾರ್ಯಾಚರಣೆಯ ನಿಯತಾಂಕಗಳು",
        interfaceProtocols: "ಇಂಟರ್ಫೇಸ್ ಪ್ರೋಟೋಕಾಲ್ಗಳು",
        telemetryAlerts: "ಟೆಲಿಮೆಟ್ರಿ ಎಚ್ಚರಿಕೆಗಳು",
        telemetryDesc: "ನೋಡ್ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ನೈಜ-ಸಮಯದ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
        darkDesc: "ಕಡಿಮೆ ಬೆಳಕಿನ ಪರಿಸರಕ್ಕಾಗಿ ದೃಶ್ಯವನ್ನು ಉತ್ತಮಗೊಳಿಸಿ",
        portalConfigTitle: "ಪೋರ್ಟಲ್ ಕಾನ್ಫಿಗರೇಶನ್",
        securityMatrix: "ಭದ್ರತಾ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
        pinRequired: "ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        criticalZone: "ಅಪಾಯಕಾರಿ ವಲಯ",
        accountTerminationDesc: "ಖಾತೆ ಮುಚ್ಚುವಿಕೆಯು ಬದಲಾಯಿಸಲಾಗದ ಕಾರ್ಯಾಚರಣೆಯ ಆಜ್ಞೆಯಾಗಿದೆ.",
        automationProtocols: "ಹಾಜರಾತಿ ಸ್ವಯಂಚಾಲಿತ ಪ್ರೋಟೋಕಾಲ್ಗಳು",
        automationSubtitle: "ಹಿನ್ನೆಲೆ ಎಂಜಿನ್ಗಳು ಮತ್ತು ಸಿಮ್ಯುಲೇಶನ್ಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ",
        automationParameters: "ಸ್ವಯಂಚಾಲಿತ ನಿಯತಾಂಕಗಳು",
        autoAbsentSweep: "ಸ್ವಯಂಚಾಲಿತ ಅನುಪಸ್ಥಿತಿ ಗುರುತು",
        autoAbsentSweepDesc: "ದಿನದ ಕೊನೆಯಲ್ಲಿ ಬಾಕಿ ಇರುವ ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಅನುಪಸ್ಥಿತಿಯೆಂದು ಗುರುತಿಸುತ್ತದೆ",
        sweepCutoffTime: "ಸ್ವೀಪ್ ಕಟ್ ಆಫ್ ಸಮಯ",
        parentEmailNotify: "ಪೋಷಕರಿಗೆ ಇಮೇಲ್ ಅಧಿಸೂಚನೆ",
        parentEmailNotifyDesc: "ಅನುಪಸ್ಥಿತಿಯ ಸಂದರ್ಭದಲ್ಲಿ ನೇರವಾಗಿ ಪೋಷಕರಿಗೆ ಇಮೇಲ್ ಕಳುಹಿಸುತ್ತದೆ",
        parentSmsNotify: "ಪೋಷಕರಿಗೆ ಎಸ್ಎಂಎಸ್ ಅಧಿಸೂಚನೆ",
        parentSmsNotifyDesc: "ಅನುಪಸ್ಥಿತಿಯ ಸಂದರ್ಭದಲ್ಲಿ ನೇರವಾಗಿ ಪೋಷಕರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ ನೈಜ-ಸಮಯದ ಎಸ್ಎಂಎಸ್ ಕಳುಹಿಸುತ್ತದೆ",
        midnightSessionReset: "ಮಧ್ಯರಾತ್ರಿ ಮರುಹೊಂದಿಕೆ",
        midnightSessionDesc: "ಸ್ವಯಂಚಾಲಿತ ದೈನಂದಿನ ಮರುಹೊಂದಿಸುವ ಚಕ್ರ",
        telemetryOverrides: "ಟೆಲಿಮೆಟ್ರಿ ಸಿಮ್ಯುಲೇಟರ್ಗಳು",
        simulationDesc: "ತ್ವರಿತ ಪ್ರದರ್ಶನ ಅಥವಾ ಪರಿಶೀಲನೆಗಾಗಿ ಹಿನ್ನೆಲೆ ಸೇವೆಗಳ ತ್ವರಿತ ಹಸ್ತಚಾಲಿತ ಸಿಮ್ಯುಲೇಶನ್ ಅನ್ನು ಒತ್ತಾಯಿಸುತ್ತದೆ.",
        simulateSweep: "ದೈನಂದಿನ ಸ್ವೀಪ್ ಸಿಮ್ಯುಲೇಶನ್",
        simulateReset: "ದೈನಂದಿನ ಮರುಹೊಂದಿಕೆ ಸಿಮ್ಯುಲೇಶನ್",
        forceSweep: "ಸ್ವೀಪ್ ಒತ್ತಾಯಿಸು",
        forceReset: "ರೀಸೆಟ್ ಒತ್ತಾಯಿಸು"
    },
    Telugu: {
        welcome: "స్వాగతం",
        facultyDashboard: "ఫ్యాకల్టీ డాష్‌బోర్డ్",
        dashboard: "డాష్‌బోర్డ్",
        overview: "అవలోకనం",
        attendanceHub: "హాజరు హబ్",
        leaveGateway: "సెలవు గేట్‌వే",
        curriculum: "పాఠ్యప్రణాళిక",
        curriculumHub: "పాఠ్యప్రణాళిక కేంద్ర",
        settings: "సెట్టింగులు",
        myIdentity: "నా గుర్తింపు",
        totalStudents: "మొత్తం విద్యార్థులు",
        avgAttendance: "సగటు హాజరు",
        pendingRecords: "పెండింగ్ రికార్డులు",
        liveClasses: "లైవ్ తరగతులు",
        registryFinalized: "రిజిస్ట్రీ పూర్తయింది",
        studentRegistry: "విద్యార్థి రిజిస్ట్రీ",
        exportMaster: "మాస్టర్ ఎగుమతి",
        viewReports: "నివేదికలు చూడండి",
        finalizeRegistry: "రిజిస్ట్రీ పూర్తి చేయండి",
        recentClassActivity: "ఇటీవలి తరగతి కార్యాచరణ",
        sessionProtocols: "సెషన్ ప్రోటోకాల్స్",
        teamMembers: "బృంద సభ్యులు",
        studentRegistryOffline: "విద్యార్థి రిజిస్ట్రీ ఆఫ్ లైన్ లో ఉంది",
        dbSyncMsg: "Zవినియోగదారు రికార్డులను సింక్రనైజ్ చేయడానికి మరియు చూడటానికి కేంద్రీయ డేటాబేస్ కు కనెక్ట్ అవ్వండి.",
        viewDirectory: "విద్యార్థుల జాబితా చూడండి",
        dbRequired: "డేటాబేస్ కనెక్షన్ అవసరం",
        facultyAttendanceEntry: "ఫ్యాకల్టీ హాజరు నమోదు",
        memberDirectory: "సభ్యుల డైరెక్టరీ",
        downloadRegistry: "రిజిస్ట్రీ డౌన్‌లోడ్",
        generateReport: "నివేదికను రూపొందించండి",
        darkInterface: "డార్క్ మోడ్",
        updateAccessKey: "యాక్సెస్ పిన్ మార్చండి",
        deleteAccount: "ఖాతా తొలగించండి",
        terminateNode: "ఖాతా రద్దు చేయండి",
        logoutSession: "లాగ్ అవుట్",
        parentSmsLogging: "తల్లిదండ్రుల ఎస్ఎంఎస్ టెలిమెట్రీ",
        outboundLogs: "వెళ్ళే ఎస్ఎంఎస్ లాగ్లు",
        sandboxGateway: "ఇంటరాక్టివ్ శాండ్‌బాక్స్ గేట్‌వే",
        transmitSandboxAlert: "టెస్ట్ ఎస్ఎంఎస్ పంపండి",
        parentMobileNo: "తల్లిదండ్రుల మొబైల్ నంబర్",
        studentNameOptional: "విద్యార్థి పేరు (ఐచ్ఛికం)",
        msgPayloadOptional: "సందేశ సమాచారం (ఐచ్ఛికం)",
        smsConsoleSubtitle: "బయటకు వెళ్ళే ఎస్ఎంఎస్ ప్రసారాలు, డెలివరీ స్థితి ఆడిటింగ్ మరియు టెస్టింగ్ ఆప్షన్లు",
        smsSandboxDesc: "మొబైల్ ప్రసారాన్ని ధృవీకరించండి. టెక్స్ట్‌బెల్ కోసం చెల్లుబాటు అయ్యే అంతర్జాతీయ సంఖ్యలు అవసరం.",
        reloadConsole: "రీలోడ్ చేయండి",
        globalLanguage: "గ్లోబల్ లాంగ్వేజ్",
        portalConfig: "పోర్టల్ కాన్ఫిగరేషన్",
        sysPreferences: "సిస్టమ్ ప్రాధాన్యతలు మరియు కార్యాచరణ పారామితులు",
        interfaceProtocols: "ఇంటర్‌ఫేస్ ప్రోటోకాల్స్",
        telemetryAlerts: "టెలిమెట్రీ అలర్ట్లు",
        telemetryDesc: "నోడ్ స్థితి గురించి నిజ-సమయ నోటిఫికేషన్‌లను పొందండి",
        darkDesc: "తక్కువ వెలుతురు వాతావరణం కోసం విజువల్ ఆప్టిమైజ్ చేయండి",
        portalConfigTitle: "పోర్టల్ కాన్ఫిగరేషన్",
        securityMatrix: "భద్రతా మ్యాట్రిక్స్",
        pinRequired: "పిన్ అవసరం",
        criticalZone: "డేంజర్ జోన్",
        accountTerminationDesc: "ఖాతా రద్దు అనేది తిరిగి మార్చలేని కార్యాచరణ ఆదేశం.",
        automationProtocols: "హాజరు ఆటోమేషన్ ప్రోటోకాల్స్",
        automationSubtitle: "బ్యాక్‌గ్రౌండ్ ఇంజన్‌లు మరియు అనుకరణలను కాన్ఫిగర్ చేయండి",
        automationParameters: "ఆటోమేషన్ పారామితులు",
        autoAbsentSweep: "ఆటోమేటెడ్ ఆబ్సెంట్ స్వీప్",
        autoAbsentSweepDesc: "రోజు చివరన పెండింగ్ లో ఉన్న విద్యార్థులను ఆటోమేటిక్ గా ఆబ్సెంట్ గా గుర్తిస్తుంది",
        sweepCutoffTime: "స్వీప్ కట్ ఆఫ్ సమయం",
        parentEmailNotify: "తల్లిదండ్రులకు ఈమెయిల్ అలర్ట్లు",
        parentEmailNotifyDesc: "ఆబ్సెంట్ అయినప్పుడు నేరుగా తల్లిదండ్రులకు ఈమెయిల్ అలర్ట్ పంపుతుంది",
        parentSmsNotify: "తల్లిదండ్రులకు ఎస్ఎంఎస్ అలర్ట్లు",
        parentSmsNotifyDesc: "ఆబ్సెంట్ అయినప్పుడు నేరుగా తల్లిదండ్రుల మొబైల్ నంబర్ కు నిజ-సమయ ఎస్ఎంఎస్ అలర్ట్ పంపుతుంది",
        midnightSessionReset: "అర్థరాత్రి రీసెట్",
        midnightSessionDesc: "ఆటోమేటిక్ రోజువారీ రీసెట్ చక్రం",
        telemetryOverrides: "టెలిమెట్రీ సిమ్యులేటర్లు",
        simulationDesc: "శీఘ్ర ప్రదర్శన లేదా ధృవీకరణ కోసం బ్యాక్‌గ్రೌಂಡ್ సేవల తక్షణ మాన్యువల్ అనుకరణను బలవంతం చేస్తుంది.",
        simulateSweep: "రోజువారీ స్వీప్ సిమ్యులేషన్",
        simulateReset: "రోజువారీ రీసెట్ సిమ్యులేషన్",
        forceSweep: "స్వీప్ వర్తింపజేయి",
        forceReset: "రీసెట్ వర్తింపజేయి"
    }
};
